services:
  postgres:
    image: postgres:16
    container_name: postgres-workshop
    restart: always
    environment:
      POSTGRES_DB: workshopdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: api-workshop
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/workshopdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
